### ISSUE TITLE
hevc encofing through qsv/vaapi is broken for Intel 11th/Tiger Lake iGPU

### ISSUE THREAD

**Issue by rnsc** [jellyfin/jellyfin-ffmpeg#90]
When trying to encode hevc files on a 11th gen Intel/Tiger Lake, you end up with a garbage encoding.
This has been flagged here on the Intel media-driver github repo: https://github.com/intel/media-driver/issues/1190

I use the Intel drivers from their public Ubuntu apt repositories:  https://repositories.intel.com/graphics/ubuntu focal main 
Package name: intel-opencl-icd 

Someone already did a patch for ffmpeg to fix this issue, following this comment:
https://github.com/intel/media-driver/issues/1190#issuecomment-963747307

The patch itself:
https://github.com/intel-media-ci/cartwheel-ffmpeg/blob/master/patches/0025-lavc-vaapi_encode_h265-fix-max_transform_hierarchy_d.patch

Given that, could we add this patch to the jellyfin-ffmpeg repo?

Small screenshot from the original bug report on the Intel github repository:
![Example from the Intel repo](https://user-images.githubusercontent.com/882016/116470023-8d4cda80-a87b-11eb-99ac-367c041acf3d.png)

I've built the Debian package locally and used it in a Docker image and now my HEVC encodings are working properly.
But I'd rather this fixed here. Unless you're against it, then I'll keep my copy.

**Comment by nyanmisaka** [comment]
It will be fixed by upgrading to [22.1.1 driver](https://github.com/intel/media-driver/pull/1312) in https://github.com/jellyfin/jellyfin-ffmpeg/pull/89

**Comment by Goblinlordx** [comment]
This is interesting in that mine breaks but not in the same way. I installed the `intel-media-va-non-free` on bullseye debian using docker container and it starts encoding when I have "hevc" encoding enabled. However, after a few minutes, it suddenly skips and then stops playing and goes to a next episode (this was with a TV series episode being played). Hopefully my issue would also be fixed with the change 👍 .

**Comment by rnsc** [comment]
Hello @nyanmisaka , I tested the new deb built and I still have the same issue.
Rebuilding with the patch I mentioned in my initial post locally produces a build that works properly (ie: no artefacts on the generated mkv)

**Comment by Shadowghost** [comment]
I'm not sure why the patch is still required though. In the issue it was mentioned to only be a temporary workaround.

**Comment by rnsc** [comment]
> I'm not sure why the patch is still required though. In the issue it was mentioned to only be a temporary workaround.

I'm not sure either, I'm willing to do tests on my Tiger Lake CPU if you have have clues as to what could be happening.

**Comment by nyanmisaka** [comment]
I will update the patch series in the next time.
